Repository CaffeineDuck/nepse-api, pull requests merged in 2021-07, with the labels that each got.

#36 update mapping
  nepse/utils.py
Labels: enhancement

#37 Revert "update mapping"
  nepse/utils.py
Labels: bug

#38 Patch updated mappping 1
  nepse/utils.py
  pyproject.toml
Labels: enhancement

#39 Adds `total_trade_value` in the `SecurityResponse`
  nepse/security/types.py
  pyproject.toml
Labels: bug

#40 Company History is now accessible through the API wrapper.
  basic_test.py
  nepse/market/core.py
  nepse/market/types.py
  nepse/security/core.py
  nepse/security/types.py
Labels: enhancement

#41 Market Summary now can be accessible through API wrapper.
  nepse/market/core.py
  nepse/market/types.py
Labels: enhancement

#43 Added Examples
  examples/check_ipo.py
  examples/discord_bot.py
  examples/get_broker.py
  examples/get_company_detailed.py
  examples/get_company_history.py
  examples/get_floorsheets.py
Labels: documentation, enhancement

#44 [Patch] Hot Fixes
  examples/check_ipo.py
  examples/discord_bot.py
Labels: bug

#46 [patch] Changed the mapping for the post request.
  nepse/utils.py
Labels: bug

#47 [patch] Fixes #27 by removing the mapping and fetching the ID from API
  nepse/utils.py
Labels: bug

#49 [Update] Removed Unnecessary if check from MarketClient
  nepse/market/core.py
Labels: minor issue

#50 Organized the tests by seperating them
  nepse/security/core.py
  nepse/security/types.py
  tests/broker_test.py
  tests/market_test.py
  tests/security_test.py
Labels: enhancement
